### ISSUE TITLE
Error in makefile found at compile time

### ISSUE THREAD

**Issue by small-leek** [kunpengcompute/KAEdriver#6]
file: https://github.com/kunpengcompute/KAEdriver/blob/master/kae_driver/hisilicon/Makefile
line：obj-$(CONFIG_CRYPTO_DEV_HISI_SEC) += sec/
error：kae_driver/hisilicon/sec does not exist

**Comment by yuhongxiao123456** [comment]
yes, you're right. This field is left blank, but it does not affect functions.

**Comment by KeyiZhong** [comment]
It is possible to meet an error due to the adapability of low-version make. When this happened, deleting the obj-$(CONFIG_CRYPTO_DEV_HISI_SEC) += sec/ line of kae_driver/hisilicon/Makefile will solve the problem
对于低版本的make，由于兼容性问题，在编译时有可能遇到error，只需将kae_driver/hisilicon/Makefile 中的obj-$(CONFIG_CRYPTO_DEV_HISI_SEC) += sec/删除即可

**Comment by yuhongxiao123456** [comment]
add more info
